version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Notes:
# - Backend is accessible as 'backend:8000' from frontend (see vite.config.js proxy)
# - Frontend is served on port 3000 (mapped to container's 80)
# - You need Dockerfiles in both backend/ and frontend/ for this to work 